

const imgConstants = {
    GET_IMAGE_REQUEST: 'IMG_GET_IMAGE_REQUEST',
    GET_IMAGE_SUCCESS: 'IMG_GET_IMAGE_SUCCESS',
    GET_IMAGE_FAILURE: 'IMG_GET_IMAGE_FAILURE',
};

export default imgConstants;